spring:
  application:
    name: ead-api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-service
      username: configserver
      password: ead-secret
  profiles:
    active: dev
